export enum ErrorCode {
  // ── Exception codes (src/common/messages/messages.response.ts → Exception) ──
  BAD_REQUEST = 't_bad_request',
  CONFLICT = 't_conflict',
  CREATED_FAILED = 't_created_failed',
  PERMISSION = 't_need_role_permission',
  UNAUTHORIZED = 't_unauthorized',
  FILE_MISSING = 't_file_missing',
  FILE_BUFFER_MISSING = 't_file_buffer_missing',
  UPLOAD_FAILED = 't_upload_failed',
  URL_MISSING = 't_url_asset_missing',
  ID_MISSING = 't_id_missing',
  ID_INVALID = 't_id_invalid',
  NOT_EXIST = 't_data_not_exist',
  EXISTED = 't_data_existed',
  EXPIRED = 't_expires',
  SIZE_INVALID = 't_size_invalid',
  UNIQUE_INVALID = 't_unique_invalid',

  // ── Invalid codes (InvalidMessageResponse) ──
  EMAIL_INVALID = 't_email_invalid',
  EMAIL_INCORRECT = 't_email_incorrect',
  NAME_EMPTY = 't_name_empty',
  NAME_MIN = 't_name_min',
  NAME_MAX = 't_name_max',
  PASSWORD_MIN = 't_password_min_invalid',
  PASSWORD_INCORRECT = 't_password_incorrect',
  ROLE_EMPTY = 't_role_empty',
  DESC_EMPTY = 't_description_empty',
  ID_EMPTY = 't_id_empty',
  GENDER_EMPTY = 't_gender_empty',
  GENDER_INVALID = 't_gender_invalid',
  OTP_MIN = 't_otp_code_min_invalid',
  GOOGLE_TOKEN = 't_google_empty',
  USER_NOT_FOUND = 't_user_not_found',
  SESSION_BAD_ACCESS = 't_session_bad_access',
  FIELD_EMPTY = 't_field_empty',
  LINEAGE_TYPE_INVALID = 't_lineage_type_invalid',
  CONTENT_EMPTY = 't_content_empty',

  // ── Valid codes (ValidMessageResponse) ──
  REGISTER_SUCCESS = 't_register_success',
  LOGIN_SUCCESS = 't_login_success',
  CREATED_SUCCESS = 't_created_success',
  UPDATED_SUCCESS = 't_updated_success',
  GETTED_SUCCESS = 't_getted_success',
  DELETED_SUCCESS = ' t_deleted_success',
}
