-- CreateEnum
CREATE TYPE "LINEAGE_TYPE" AS ENUM ('PATRIARCHAL', 'MATRIARCHAL', 'OTHER');

-- AlterTable
ALTER TABLE "family" ADD COLUMN     "lineageType" "LINEAGE_TYPE" NOT NULL DEFAULT 'PATRIARCHAL';
